// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_POSTGRES_POSTGRES_H
#define ANALYZER_PROTOCOL_POSTGRES_POSTGRES_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "postgres_pac.h"

namespace analyzer { namespace Postgres {

class POSTGRES_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	POSTGRES_Analyzer(Connection* conn);
	virtual ~POSTGRES_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);
	

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new POSTGRES_Analyzer(conn); }

protected:
	binpac::POSTGRES::POSTGRES_Conn* interp;
	
	bool had_gap;
	
};

} } // namespace analyzer::* 

#endif