# Generated by binpac_quickstart

signature dpd_mongodb {
    
    ip-proto == tcp
    

    # ## TODO: Define the payload. When Bro sees this regex, on
    # ## any port, it will enable your analyzer on that
    # ## connection.
    # ## payload /^MONGODB/

    enable "mongodb"
}

#signature dpd_mongodb_client {
#   ip-proto == tcp
#   payload /^[\x00~\xff]{12}[\xd1-\xdd]\x07\x00\x00/
#   tcp-state originator
#   enable "mongodb"
#}
#
#
#signature dpd_mongodb_server {
#   ip-proto == tcp
#   payload /^[\x00-xff]{12}\x01\x00\x00\00/
#   tcp-state responder
#   requires-reverse-signature dpd_mongodb_client
#   enable "mongodb"
#}