// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_MONGODB_MONGODB_H
#define ANALYZER_PROTOCOL_MONGODB_MONGODB_H

#include "events.bif.h"


#include "analyzer/protocol/tcp/TCP.h"

#include "mongodb_pac.h"

namespace analyzer { namespace mongodb {

class MONGODB_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	MONGODB_Analyzer(Connection* conn);
	virtual ~MONGODB_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();

	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64 seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);

	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new MONGODB_Analyzer(conn); }

protected:
	binpac::MONGODB::MONGODB_Conn* interp;
	bool had_gap;

};

} } // namespace analyzer::*

#endif
